name: render

on:
  repository_dispatch:
    types: [render_weather_card]

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pillow

      - name: Render weather card
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python scripts/render.py

      - name: Commit & push result
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add weather/*.png
          git commit -m "render: ${{ github.event.client_payload.job_id }}" || echo "nothing to commit"
          git push
